name: gimp
version: 2.9.4-1
summary: GIMP (GNU Image Manipulation Program) - development version
description: GTetrinet is a clone of Tetrinet, a multiplayer tetris variant for
 GIMP is an advanced picture editor. You can use it to edit, enhance, and
 retouch photos and scans, create drawings, and make your own images.

 This package includes the GIMP development version with latest features.

apps:
  run:
    command: launcher
    plugs: [home, unity7, x11, network]

parts:
  launcher:
    plugin: copy
    files:
      launcher: bin/launcher
  libmypaint:
    plugin: autotools
    source-type: git
    source: https://github.com/mypaint/libmypaint.git
    source-branch: master
    build-packages:
            - autotools-dev
            - libjson-c-dev
            - intltool
    snap:
            - -usr/include

  gimp:
    after: [libmypaint]
    plugin: autotools
#    configflags: [--includedir=../../parts/libmypaint/install/include]
    configflags: [--prefix=/usr, --sysconfdir=$SNAP/etc, --datarootdir=$SNAP/usr/share, --datadir=$SNAP/usr/share, --disable-python, --with-lcms=lcms2]
    source-type: git
    source: https://git.gnome.org/browse/gimp
    source-tag: GIMP_2_9_4
    build-packages:
            - autotools-dev
            - dh-autoreconf
            - gegl 
            - gettext
            - gnome-pkg-tools
            - gtk-doc-tools
            - intltool
            - iso-codes
            - libaa1-dev
            - libart-2.0-dev
            - libasound2-dev
            - libatk1.0-dev
            - libbabl-dev
            - libbz2-dev
            - libcairo2-dev
            - libcurl4-gnutls-dev
            - libdbus-glib-1-dev
            - libexif-dev
            - libfreetype6-dev
            - libfontconfig1-dev
            - libgegl-dev
            - libglib2.0-dev
            - libglib2.0-doc
            - libgexiv2-dev
            - libgtk2.0-dev
            - libgtk2.0-doc
            - libgdk-pixbuf2.0-dev
            - libgdk-pixbuf2.0-doc
            - libgs-dev
            - libgudev-1.0-dev
            - libice-dev
            - libjpeg-dev
            - liblcms2-dev
            - libmng-dev
            - libpango1.0-dev
            - libpng-dev
            - libpoppler-glib-dev
            - librsvg2-dev
            - libsm-dev
            - libtiff5-dev
            - libwmf-dev
            - libx11-dev
            - libxcursor-dev
            - libxmu-dev
            - libxpm-dev
            - libxt-dev
            - mypaint
            - zlib1g-dev
            - patchutils
            - python-dev
            - python2.7-dev
            - python2.7
            - python3
            - python3-cairo
            - libpython2.7-dev
            - python-cairo
            - python-gtk2-dev
            - xsltproc
    stage-packages:
            - dmz-cursor-theme
            - gettext
            - gegl
            - gnome-settings-daemon-schemas
            - gsettings-desktop-schemas
            - libaa1
            - libbabl-0.1-0
            - libbz2-1.0
            - libc6
            - libcairo2
            - libdbus-1-3
            - libdbus-glib-1-2
            - libexif12
            - libfontconfig1
            - libfreetype6
            - libgegl-0.3-0
            - libgdk-pixbuf2.0-0
            - libgs9
            - libgtk2.0-0
            - libgudev-1.0-0
            - libjasper1
            - libjpeg8
            - liblcms2-2
            - libmng2
            - libxkbcommon0
            - libpango-1.0-0
            - libpangocairo-1.0-0
            - libpangoft2-1.0-0
            - libpng16-16
            - libpoppler-glib8
            - librsvg2-2
            - libtiff5
            - libwmf0.2-7
            - light-themes
            - mypaint
            - shared-mime-info
            - ttf-ubuntu-font-family
            - xsltproc
            - zlib1g
